on:
  push:
    branches: [main]
    paths:
      - "infra/**"
  pull_request: 
    branches: [main]
    paths:
      - "infra/**"
  workflow_dispatch:
  
permissions:
  id-token: write # This is required for requesting the JWT(JSON Web Token) through OIDC
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for adding Terraform plan detail as comment to the PR

env:
  AWS_REGION: "ap-southeast-2"
  WORKING_DIR: "infra/"
  TF_VERSION: "1.10.1"

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::249133131018:role/ecommerce-cicd-deployment-role"
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: "GitHubActionsSession"

      - name: Validate the role works
        run: aws s3 ls s3://ecommerce-data-ww/ecommerce-raw/